### ISSUE TITLE
strange ValueError (on branch xpar-ypar-plot)

### ISSUE THREAD

**Issue by harrispilton** [mijowild/fieldcycling#5]
When starting the first experiment loads fine. When I come back to the first experiment, after changing slider to some other value (say: 144 for example) I get a error message, and the plot doesn't update.
ERROR:bokeh.server.protocol.server_handler:error handling message Message 'PATCH-DOC' (revision 1): ValueError('Shape of passed values is (2, 16000), indices imply (2, 32000)',)

**Comment by mijowild** [comment]
cannot reproduce, 144 works fine for me. For 145 I get 'ERROR:bokeh.server.protocol.server_handler:error handling message Message 'PATCH-DOC' (revision 1): KeyError(145,)', but that's probably b/c it's the last experiment

**Comment by harrispilton** [comment]
This might be specific to the machine :( I alway run on powerful win10, slow win7, and intermediate mac.

It works on the win10 machine. But I will test again.

the KeyError, can be fixed by correcting the slider range

**Comment by harrispilton** [comment]
tested today on slow win7 without problem
